name: travel_lanka
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  intl: ^0.20.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/1.jpg

flutter_icons:
  android: true
  ios: false
  image_path: assets/2.png